// <auto-generated />
using System;
using ASKOmaster;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ASKOmaster.Migrations
{
    [DbContext(typeof(SparePartsContext))]
    partial class SparePartsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ASKOmaster.Jobs", b =>
                {
                    b.Property<string>("idoss")
                        .HasColumnType("text");

                    b.Property<string>("art")
                        .HasColumnType("text");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("model")
                        .HasColumnType("text");

                    b.Property<string[]>("parts")
                        .HasColumnType("text[]");

                    b.Property<string>("tech")
                        .HasColumnType("text");

                    b.Property<string>("warranty")
                        .HasColumnType("text");

                    b.Property<string>("wos")
                        .HasColumnType("text");

                    b.HasKey("idoss");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("ASKOmaster.Release", b =>
                {
                    b.Property<string>("sap")
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("dn")
                        .HasColumnType("text");

                    b.Property<string>("part")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("sap");

                    b.ToTable("Release");
                });
#pragma warning restore 612, 618
        }
    }
}
